services:
    backend:
        build: 
            context: ./server
        volumes:
            - ./server/src:/code/src
            - .env:/code/.env
        environment:
            - NODE_ENV=production
            # PG_PASSWORD: /run/secrets/db_password
        env_file:
            - .env
        ports:
            - "3000:3000"
        networks:
            - client-side
            - server-side
        # healthcheck: 
        #   test: ["CMD", "curl", "-f", "http://localhost"]
        #   interval: 15s
        #   timeout: 5s
        #   retries: 3
        #   start_period: 10s
        depends_on:
            - db
    frontend:
        build: 
            context: ./client-app
        volumes:
            - ./client-app/src:/code/src
            - .env:/code/.env
        env_file:
            - .env
        ports:
            - "4200:4200"
        networks:
            - client-side
        # depends_on:
        #     - backend
    db:
        image: postgres:16-bullseye
        restart: always
        env_file:
            - .env
        networks:
            - server-side
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
networks:
    client-side: {}
    server-side: {}
volumes:
    db-data: {}

# secrets:
#     db-password:
#         file: password.txt